[[main]]
name = "About Me"
url = "#about"
weight = 10

[[main]]
name = "Experience"
url = "#experience"
weight = 30

# [[main]]
# name = "Skills"
# url = "#education"
# weight = 20

[[main]]
name = "Projects"
url = "#projects"
weight = 40

[[main]]
name = "Activities"
url = "#activities"
weight = 50

[[main]]
name = "CV"
url = "cv"
weight = 60

[[main]]
name = "Contact"
url = "#contact"
weight = 70
